#!/usr/bin/env python3
"""Validate the source catalog and render its Markdown views (standard library only)."""

import argparse
from collections import Counter
from datetime import date
import json
from pathlib import Path
import re
import sys
from urllib.parse import urlsplit

from figures import render_credits, render_interface, validate_figures

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "models.json"
FIGURES = ROOT / "data" / "figures.json"
VOICEBENCH = ROOT / "data" / "voicebench.json"
CATEGORIES = {
    "omni": ("Omni and audio-visual models", "omni.md", "Omni"),
    "speech": ("Speech dialogue models", "speech.md", "Speech"),
    "audio": ("Audio understanding models", "audio.md", "Audio"),
    "asr": ("Speech recognition language models", "asr.md", "LLM-ASR"),
    "pipeline": ("VoiceBench cascaded systems", "pipelines.md", "Cascade"),
}
RELEASE_STATUS = {"open-license": "Open license", "restricted": "Custom / restricted", "unclear": "License unclear"}
MODALITIES = {"T", "I", "V", "A", "S", "M", "X"}
INTERACTIONS = {"generation", "text-output", "streaming", "full-duplex", "not-specified"}
CODE_LICENSES = {"Apache-2.0", "MIT", "MIT / Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "MPL-2.0", "GPL-3.0", "GPL-3.0-only", "GPL-3.0-or-later", "AGPL-3.0-only", "AGPL-3.0-or-later"}
WEIGHT_LICENSES = CODE_LICENSES | {"CC-BY-4.0", "CC-BY-SA-4.0", "CC0-1.0", "OpenMDW-1.1"}
SOURCE_KINDS = {"paper", "repository", "model-card", "documentation", "announcement", "project"}
REVIEWS = {"abstract", "paper-sections", "readme", "model-card", "documentation", "announcement", "project"}
LEGEND = "**Modalities:** T = text, I = image, V = video, A = general audio, S = speech, M = music, X = other structured modalities. A is a broad label, not a guarantee of every audio task. See the [methodology](../docs/methodology.md) for interaction labels, variant scope and inclusion rules."
GENERATED = "<!-- Generated by scripts/catalog.py from data/models.json and data/figures.json. Edit the JSON, then regenerate. -->"


def cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")


def sorted_models(models):
    return sorted(models, key=lambda m: (m["name"].casefold(), m["id"]))


def link(model, prefix=""):
    return f'{prefix}models/{CATEGORIES[model["category"]][1]}#{model["id"]}'


def io(model):
    return f'{", ".join(model["inputs"])} → {", ".join(model["outputs"])}'


def sources(model):
    labels = {"paper": "Paper", "repository": "Repository", "model-card": "Model card", "documentation": "Docs", "announcement": "Announcement", "project": "Project"}
    totals = Counter(s["kind"] for s in model["sources"])
    seen = Counter()
    links = []
    for source in model["sources"]:
        kind = source["kind"]
        seen[kind] += 1
        label = labels[kind] + (f" {seen[kind]}" if totals[kind] > 1 else "")
        links.append(f'[{label}]({source["url"]})')
    return " · ".join(links)


def resources(model):
    release = model["release"]
    covered = {release[key] for key in ("code_url", "weights_url", "code_license_url", "weights_license_url")}
    for component in release["components"]:
        covered.update({component["weights_url"], component["weights_license_url"]})
    # Keep the card short; the detail record and timeline retain all evidence.
    other = [s for s in model["sources"] if s["url"] not in covered and s["kind"] in {"paper", "project", "announcement"}][:2]
    parts = [sources({"sources": other})] if other else []
    parts += [f'[Code]({release["code_url"]})', f'[Weights]({release["weights_url"]})']
    parts += [f'[{c["role"]} weights]({c["weights_url"]})' for c in release["components"]]
    return " · ".join(parts)


def license_links(model):
    release = model["release"]
    text = f'**{RELEASE_STATUS[release["status"]]}:** code [{release["code_license"]}]({release["code_license_url"]}) · weights [{release["weights_license"]}]({release["weights_license_url"]})'
    text += "".join(f' · {c["role"]} [{c["weights_license"]}]({c["weights_license_url"]})' for c in release["components"])
    if release["license_notes"]:
        text += f' — {release["license_notes"]}'
    return text


def iso_date(value, context):
    if not isinstance(value, str) or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
        raise ValueError(f"{context}: expected YYYY-MM-DD")
    return date.fromisoformat(value)


def validate(catalog):
    if catalog.get("schema_version") != 3:
        raise ValueError("Unsupported schema_version")
    cutoff = iso_date(catalog["as_of"], "as_of")
    models = catalog["models"]
    if not isinstance(models, list) or not models:
        raise ValueError("models must be a nonempty list")
    ids, names = set(), set()
    required = {"id", "name", "category", "inputs", "outputs", "interaction", "summary", "architecture", "notes", "variants", "source_date", "source_date_kind", "sources", "release"}
    for m in models:
        if set(m) != required:
            raise ValueError(f'{m.get("id", "entry")}: unexpected/missing fields: {set(m) ^ required}')
        mid = m["id"]
        if not isinstance(mid, str) or not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", mid) or mid in ids:
            raise ValueError(f"Invalid or duplicate id: {mid}")
        ids.add(mid)
        for field in ("name", "summary", "architecture", "notes"):
            if not isinstance(m[field], str) or not m[field].strip():
                raise ValueError(f"{mid}: {field} must contain text")
        if len(m["summary"]) > 240 or "\n" in m["summary"] or len(m["summary"].split()) < 5:
            raise ValueError(f"{mid}: summary must be a short explanation of what the model does")
        if m["name"].casefold() in names:
            raise ValueError(f'{mid}: duplicate name; disambiguate separate models')
        names.add(m["name"].casefold())
        if m["category"] not in CATEGORIES or m["interaction"] not in INTERACTIONS:
            raise ValueError(f"{mid}: unknown category or interaction")
        for field in ("inputs", "outputs"):
            values = m[field]
            if not isinstance(values, list) or not values or not all(isinstance(x, str) for x in values) or len(values) != len(set(values)) or not set(values) <= MODALITIES:
                raise ValueError(f"{mid}: invalid {field}")
        variants = m["variants"]
        if not isinstance(variants, list) or not all(isinstance(v, str) and v.strip() for v in variants) or len(variants) != len(set(variants)):
            raise ValueError(f"{mid}: invalid variants")
        if m["source_date"] is None:
            if m["source_date_kind"] is not None:
                raise ValueError(f"{mid}: date kind requires a date")
        elif iso_date(m["source_date"], mid) > cutoff or m["source_date_kind"] not in {"paper", "announcement"}:
            raise ValueError(f"{mid}: invalid or future source date")
        if not isinstance(m["sources"], list) or not m["sources"]:
            raise ValueError(f"{mid}: at least one primary source required")
        urls = set()
        for source in m["sources"]:
            if set(source) != {"kind", "title", "url", "reviewed_on", "review_level"}:
                raise ValueError(f"{mid}: invalid source fields")
            url = urlsplit(source["url"])
            if url.scheme != "https" or not url.netloc or url.username or url.password or source["url"] in urls or re.search(r"\s", source["url"]):
                raise ValueError(f"{mid}: invalid/duplicate HTTPS source")
            urls.add(source["url"])
            if source["kind"] not in SOURCE_KINDS or source["review_level"] not in REVIEWS or not source["title"].strip():
                raise ValueError(f"{mid}: invalid source metadata")
            if iso_date(source["reviewed_on"], mid) > cutoff:
                raise ValueError(f"{mid}: source reviewed after cutoff")
        if m["source_date_kind"] == "paper" and not any(s["kind"] == "paper" for s in m["sources"]):
            raise ValueError(f"{mid}: paper date without a paper source")
        if not {"A", "S", "M"} & set(m["inputs"]):
            raise ValueError(f"{mid}: an audio or speech input is required")
        if m["category"] == "omni" and not ("T" in m["inputs"] and {"I", "V"} & set(m["inputs"])):
            raise ValueError(f"{mid}: omni entries also require text and visual inputs")
        if m["category"] == "speech" and not {"S", "A"} & set(m["outputs"]):
            raise ValueError(f"{mid}: speech dialogue entries require audio output")
        release = m["release"]
        release_fields = {"checkpoint", "code_url", "weights_url", "code_license", "weights_license", "code_license_url", "weights_license_url", "weights_revision", "reviewed_on", "status", "license_notes", "components"}
        if not isinstance(release, dict) or set(release) != release_fields:
            raise ValueError(f"{mid}: complete public release evidence is required")
        if not all(isinstance(release[key], str) and release[key].strip() for key in release_fields - {"components", "license_notes"}):
            raise ValueError(f"{mid}: release fields must contain text")
        if release["status"] not in RELEASE_STATUS or not isinstance(release["license_notes"], str):
            raise ValueError(f"{mid}: invalid license status or notes")
        if release["status"] != "open-license" and not release["license_notes"].strip():
            raise ValueError(f"{mid}: custom or unclear licenses require a visible explanation")
        if release["status"] == "open-license" and (release["code_license"] not in CODE_LICENSES or release["weights_license"] not in WEIGHT_LICENSES):
            raise ValueError(f"{mid}: an open-license label requires open code and weight licenses")
        for field in ("code_url", "weights_url", "code_license_url", "weights_license_url"):
            url = urlsplit(release[field])
            if url.scheme != "https" or not url.netloc or url.username or url.password or re.search(r"\s", release[field]) or release[field] not in urls:
                raise ValueError(f"{mid}: {field} must cite a primary HTTPS source")
        repository_revision = re.fullmatch(r"[0-9a-f]{40}", release["weights_revision"])
        archive_etag = re.fullmatch(r"http-etag:[A-Za-z0-9_-]+", release["weights_revision"])
        if not repository_revision and not (archive_etag and urlsplit(release["weights_url"]).path.endswith(".tar.gz") and "ETag" in m["notes"]):
            raise ValueError(f"{mid}: checkpoint requires a full commit hash or a documented archive HTTP ETag")
        if iso_date(release["reviewed_on"], mid) > cutoff:
            raise ValueError(f"{mid}: release reviewed after cutoff")
        components = release["components"]
        if not isinstance(components, list) or bool(components) != (m["category"] == "pipeline"):
            raise ValueError(f"{mid}: only cascades require additional checkpoint components")
        for component in components:
            if set(component) != {"role", "checkpoint", "weights_url", "weights_license", "weights_license_url", "weights_revision"} or not all(isinstance(v, str) and v.strip() for v in component.values()):
                raise ValueError(f"{mid}: incomplete cascade component")
            if not re.fullmatch(r"[0-9a-f]{40}", component["weights_revision"]):
                raise ValueError(f"{mid}: component revision must be a full commit hash")
            if not {component["weights_url"], component["weights_license_url"]} <= urls:
                raise ValueError(f"{mid}: cascade component evidence must cite primary sources")
            if release["status"] == "open-license" and component["weights_license"] not in WEIGHT_LICENSES:
                raise ValueError(f"{mid}: restricted cascade component cannot be labeled open-license")
        if m["interaction"] == "full-duplex" and not ({"S", "A"} & set(m["inputs"]) and {"S", "A"} & set(m["outputs"])):
            raise ValueError(f"{mid}: spoken full-duplex requires audio input and output")


def render_category(key, models, cutoff, figures):
    title = CATEGORIES[key][0]
    lines = [f"# {title}", "", GENERATED, "", "[← All models](../README.md#models)", "", f"**{len(models)} models · Reviewed {cutoff}**", "", "Primary-source figures and labeled input/output diagrams. [Figure credits](../assets/architectures/CREDITS.md).", "", '<details>', '<summary>Model index and modality key</summary>', "", LEGEND, "", "Dates refer to papers or announcements, not necessarily model releases.", "", "| Model | Source date | Input → output | Interaction |", "| --- | --- | --- | --- |"]
    for m in models:
        lines.append(f'| [{cell(m["name"])}](#{m["id"]}) | {m["source_date"] or "—"} | {io(m)} | {m["interaction"]} |')
    lines += ["", "</details>", "", "## Architectures", ""]
    for m in models:
        figure = figures[m["id"]]
        visual_type = "Input/output diagram" if figure["kind"] == "io-diagram" else figure["locator"]
        lines += [
            f'<a id="{m["id"]}"></a>', "", f'### {m["name"]}', "",
            m["summary"], "", f'**Architecture:** {m["architecture"].rstrip(".")}.', "", resources(m), "", license_links(m), "",
            f'![{cell(m["name"])} — {visual_type}](../{figure["path"]})', "",
            f'*{visual_type} · [Source]({figure["source_url"]})*', "",
            "<details>", "<summary>Details</summary>", "",
            f'**Input → output:** {io(m)} · **Interaction:** {m["interaction"]}', "", m["notes"], "",
        ]
        if figure["kind"] == "io-diagram":
            lines += ["Editorial summary of documented inputs and outputs; internal architecture is not shown.", ""]
        if m["variants"]:
            lines += ["**Variants:** " + "; ".join(m["variants"]) + ".", ""]
        lines += ["</details>", ""]
    return "\n".join(lines).rstrip() + "\n"


def render_readme(catalog, figures):
    models = sorted_models(catalog["models"])
    counts = Counter(m["category"] for m in models)
    statuses = Counter(m["release"]["status"] for m in models)
    lines = [
        "# Awesome Omni Architectures [![Awesome](https://awesome.re/badge.svg)](https://awesome.re)", "", GENERATED, "",
        "A visual catalog of omni, speech and audio language models with public code and weights. Every entry has a short description, a diagram, code and checkpoint links.", "",
        f'**{len(models) - counts["pipeline"]} models + {counts["pipeline"]} cascaded systems · Reviewed {catalog["as_of"]}**', "",
        "[Model list](#models) · [All diagrams](#model-figures) · [VoiceBench coverage](docs/voicebench.md) · [Research](docs/research.md) · [Timeline](docs/timeline.md) · [Scope](docs/methodology.md)", "",
        f'Licenses: **{statuses["open-license"]} open · {statuses["restricted"]} custom/restricted · {statuses["unclear"]} unclear**. Downloadable weights do not always mean an unrestricted open-source license; each card shows the applicable terms.', "",
        "| Collection | Entries |", "| --- | ---: |",
    ]
    for key, (title, filename, _) in CATEGORIES.items():
        lines.append(f'| [{title}](models/{filename}) | {counts[key]} |')
    lines += [
        "",
        "## Models", "",
        "T: text · I: image · V: video · A: audio · S: speech · M: music · X: other. [Scope and labels](docs/methodology.md#modalities-and-interaction).", "",
        "<details>", f"<summary>Alphabetical model list · {len(models)} entries</summary>", "",
        "| Model | Group | Input → output | Release |", "| --- | --- | --- | --- |",
    ]
    for m in models:
        release = m["release"]
        lines.append(f'| [{cell(m["name"])}](#{m["id"]}) | {CATEGORIES[m["category"]][2]} | {io(m)} | {RELEASE_STATUS[release["status"]]} |')
    lines += ["", "</details>", "", '<a id="architectures"></a>', "", "## Model figures", "", "Figures are credited to their sources. Editorial input/output diagrams are labeled. [Credits](assets/architectures/CREDITS.md).", ""]
    for m in models:
        figure = figures[m["id"]]
        visual_type = "Input/output diagram" if figure["kind"] == "io-diagram" else figure["locator"]
        lines += [
            f'<a id="{m["id"]}"></a>', "", f'### {m["name"]}', "",
            m["summary"], "",
            f'{resources(m)} · [Details]({link(m)})', "", license_links(m), "",
            f'![{cell(m["name"])} — {visual_type}]({figure["path"]})', "",
            f'*{visual_type} · [Source]({figure["source_url"]})*', "",
        ]
    lines += [
        "", "---", "",
        "[JSON catalog](data/models.json) · [Apache 2.0](LICENSE) · [Third-party figure notice](assets/architectures/FIGURE_NOTICE.md)", "",
    ]
    return "\n".join(lines)


def render_timeline(catalog):
    known = [m for m in catalog["models"] if m["source_date"]]
    unknown = sorted_models([m for m in catalog["models"] if not m["source_date"]])
    known.sort(key=lambda m: (m["source_date"], m["name"].casefold()), reverse=True)
    lines = ["# Paper and announcement timeline", "", GENERATED, "", "[← Model index](../README.md#models)", "", f'Reviewed as of **{catalog["as_of"]}**. {len(known)} entries have a verified source date; {len(unknown)} are undated in this catalog.', "", "These are dates of the linked paper or explicitly dated announcement. An arXiv submission can precede or follow model/weights/API availability. A paper's first submission date can also precede the release of variants discussed in later revisions. Repository updates, API snapshot suffixes and model training cutoffs are not treated as release dates.", "", "| Source date | Model | Date type | Primary sources |", "| --- | --- | --- | --- |"]
    for m in known:
        lines.append(f'| {m["source_date"]} | [{cell(m["name"])}]({link(m, "../")}) | {m["source_date_kind"]} | {sources(m)} |')
    lines += ["", "## No established source date", "", "These entries remain searchable without assigning a guessed publication or release date.", ""]
    lines += [f'- [{m["name"]}]({link(m, "../")})' for m in unknown]
    return "\n".join(lines).rstrip() + "\n"


def validate_voicebench(snapshot, catalog):
    """Require an explicit disposition for every Open row in the pinned snapshot."""
    if snapshot.get("schema_version") != 1:
        raise ValueError("Unsupported VoiceBench schema_version")
    if iso_date(snapshot["as_of"], "VoiceBench as_of") > iso_date(catalog["as_of"], "as_of"):
        raise ValueError("VoiceBench snapshot is newer than the catalog")
    revision = snapshot["source_revision"]
    if not re.fullmatch(r"[0-9a-f]{40}", revision) or snapshot["source_url"] != f"https://github.com/MatthewCYM/VoiceBench/blob/{revision}/docs/index.html":
        raise ValueError("VoiceBench requires a pinned primary-source snapshot")
    rows = snapshot["rows"]
    if len(rows) != snapshot["open_rows"] or len(rows) + len(snapshot["excluded_closed"]) != snapshot["total_rows"]:
        raise ValueError("VoiceBench snapshot counts do not match its rows")
    names, references = set(), set()
    ids = {m["id"] for m in catalog["models"]}
    for row in rows:
        if set(row) != {"name", "architecture", "catalog_id", "status", "note", "evidence_urls"} or not row["name"] or row["name"] in names:
            raise ValueError("Invalid or duplicate VoiceBench row")
        names.add(row["name"])
        if row["status"] == "listed":
            if row["catalog_id"] not in ids or row["catalog_id"] in references:
                raise ValueError("VoiceBench row needs a distinct catalog checkpoint/system")
            references.add(row["catalog_id"])
        elif row["status"] == "checkpoint-unverified":
            if row["catalog_id"] is not None or not row["note"].strip() or not row["evidence_urls"]:
                raise ValueError("Unverified VoiceBench checkpoints need an explanation and evidence")
        else:
            raise ValueError("Unknown VoiceBench coverage status")
        for url in row["evidence_urls"]:
            parsed = urlsplit(url)
            if parsed.scheme != "https" or not parsed.netloc or parsed.username or parsed.password or re.search(r"\s", url):
                raise ValueError("VoiceBench evidence must use primary HTTPS URLs")


def render_voicebench(snapshot, catalog):
    models = {m["id"]: m for m in catalog["models"]}
    included = sum(r["status"] == "listed" for r in snapshot["rows"])
    lines = ["# VoiceBench coverage", "", "<!-- Generated from data/voicebench.json and data/models.json. -->", "",
             "[← Model list](../README.md#models)", "",
             f'**Reviewed {snapshot["as_of"]}: {snapshot["open_rows"]} Open leaderboard rows; {included} mapped to public releases/systems, {snapshot["open_rows"] - included} exact checkpoints unverified.**', "",
             f'[Live leaderboard]({snapshot["leaderboard_url"]}) · [Pinned source snapshot]({snapshot["source_url"]})', "",
             '“Open” is the benchmark’s label, not a license certification. Our cards distinguish open licenses, custom/research restrictions and missing license declarations. Cascaded ASR + LLM baselines are counted as systems.', "",
             "| VoiceBench entry | Catalog / release status | Notes |", "| --- | --- | --- |"]
    for row in snapshot["rows"]:
        model = models.get(row["catalog_id"])
        target = f'[{cell(model["name"])}]({link(model, "../")}) · {RELEASE_STATUS[model["release"]["status"]]}' if model else "Exact checkpoint unverified"
        evidence = " · ".join(f'[Evidence {i + 1}]({u})' for i, u in enumerate(row["evidence_urls"]))
        lines.append(f'| {cell(row["name"])} | {target} | {cell(row["note"])} {evidence} |')
    lines += ["", "Closed rows excluded: " + "; ".join(snapshot["excluded_closed"]) + ".", "",
              "Benchmark configurations and interaction labels can differ from the capabilities of the released checkpoint. The catalog records the selected checkpoint, rather than copying the benchmark’s architecture label.", ""]
    return "\n".join(lines)


def validate_local_links(outputs):
    """Check generated links and authored Markdown links against local files/anchors."""
    pages = {p: p.read_text(encoding="utf-8") for p in ROOT.rglob("*.md") if ".git" not in p.parts and p.name != "model-template.md"}
    pages.update(outputs)
    anchor_cache = {}
    for path, content in pages.items():
        anchors = set(re.findall(r'<a\s+id="([^"]+)"', content))
        for heading in re.findall(r"^#{1,6}\s+(.+)$", content, re.M):
            slug = re.sub(r"[^\w\- ]", "", heading.lower()).replace(" ", "-")
            anchors.add(slug)
        anchor_cache[path] = anchors
    for path, content in pages.items():
        # Fenced code examples are not navigable Markdown links.
        content = re.sub(r"```.*?```", "", content, flags=re.S)
        targets = re.findall(r"\[[^\]\n]*\]\(([^)\s]+)\)", content)
        targets += re.findall(r'<(?:img|a)\s+[^>]*?(?:src|href)="([^"]+)"', content)
        # Linked image previews contain an outer link around the image.
        targets += re.findall(r"\[!\[[^\]]*\]\([^)]+\)\]\(([^)]+)\)", content)
        for target in targets:
            if urlsplit(target).scheme or target.startswith("//"):
                continue
            relative, _, anchor = target.partition("#")
            dest = (path.parent / relative).resolve() if relative else path
            if dest not in pages and not dest.exists():
                raise ValueError(f"{path.relative_to(ROOT)}: missing link target {target}")
            if anchor and dest in anchor_cache and anchor not in anchor_cache[dest]:
                raise ValueError(f"{path.relative_to(ROOT)}: missing anchor {target}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate without modifying files; fail on stale generated files")
    args = parser.parse_args()
    try:
        catalog = json.loads(DATA.read_text(encoding="utf-8"))
        validate(catalog)
        voicebench = json.loads(VOICEBENCH.read_text(encoding="utf-8"))
        validate_voicebench(voicebench, catalog)
        models = sorted_models(catalog["models"])
        manifest = json.loads(FIGURES.read_text(encoding="utf-8"))
        validate_figures(catalog, manifest, ROOT)
        figures = manifest["models"]
        outputs = {
            ROOT / "README.md": render_readme(catalog, figures),
            ROOT / "docs/timeline.md": render_timeline(catalog),
            ROOT / "docs/voicebench.md": render_voicebench(voicebench, catalog),
            ROOT / "assets/architectures/CREDITS.md": render_credits(models, manifest),
        }
        for model in models:
            figure = figures[model["id"]]
            if figure["kind"] == "io-diagram":
                outputs[ROOT / figure["path"]] = render_interface(model)
        for key, (_, filename, _) in CATEGORIES.items():
            outputs[ROOT / "models" / filename] = render_category(key, [m for m in models if m["category"] == key], catalog["as_of"], figures)
        validate_local_links(outputs)
        stale = []
        for path, content in outputs.items():
            if args.check:
                if not path.exists() or path.read_text(encoding="utf-8") != content:
                    stale.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
        if stale:
            raise ValueError("Stale generated files: " + ", ".join(stale) + "; run python3 scripts/catalog.py")
        unique_sources = {s["url"] for m in models for s in m["sources"]}
        print(f'{"Checked" if args.check else "Rendered"} {len(models)} public model/system entries, {len(unique_sources)} unique primary sources, {len(figures)} visuals; release evidence, VoiceBench coverage, catalog integrity, figure assets and local links OK.')
    except (ValueError, KeyError, TypeError, OSError) as exc:
        print(f"Catalog error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
