#!/usr/bin/env python3
"""Validate the source catalog and render its Markdown views (standard library only)."""

import argparse
from collections import Counter
from datetime import date
import json
from pathlib import Path
import re
import sys
from urllib.parse import urlsplit

from figures import render_credits, render_interface, validate_figures

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "models.json"
FIGURES = ROOT / "data" / "figures.json"
CATEGORIES = {
    "omni": ("Open-source omni models", "omni.md", "Omni"),
}
MODALITIES = {"T", "I", "V", "A", "S", "M", "X"}
INTERACTIONS = {"generation", "text-output", "streaming", "full-duplex", "not-specified"}
CODE_LICENSES = {"Apache-2.0", "MIT", "BSD-2-Clause", "BSD-3-Clause", "ISC", "MPL-2.0", "GPL-3.0-only", "GPL-3.0-or-later", "AGPL-3.0-only", "AGPL-3.0-or-later"}
WEIGHT_LICENSES = CODE_LICENSES | {"CC-BY-4.0", "CC-BY-SA-4.0", "CC0-1.0"}
SOURCE_KINDS = {"paper", "repository", "model-card", "documentation", "announcement", "project"}
REVIEWS = {"abstract", "readme", "model-card", "documentation", "announcement", "project"}
LEGEND = "**Modalities:** T = text, I = image, V = video, A = general audio, S = speech, M = music, X = other structured modalities. A is a broad label, not a guarantee of every audio task. See the [methodology](../docs/methodology.md) for interaction labels, variant scope and inclusion rules."
GENERATED = "<!-- Generated by scripts/catalog.py from data/models.json and data/figures.json. Edit the JSON, then regenerate. -->"


def cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")


def sorted_models(models):
    return sorted(models, key=lambda m: (m["name"].casefold(), m["id"]))


def link(model, prefix=""):
    return f'{prefix}models/{CATEGORIES[model["category"]][1]}#{model["id"]}'


def io(model):
    return f'{", ".join(model["inputs"])} → {", ".join(model["outputs"])}'


def sources(model):
    labels = {"paper": "Paper", "repository": "Repository", "model-card": "Model card", "documentation": "Docs", "announcement": "Announcement", "project": "Project"}
    totals = Counter(s["kind"] for s in model["sources"])
    seen = Counter()
    links = []
    for source in model["sources"]:
        kind = source["kind"]
        seen[kind] += 1
        label = labels[kind] + (f" {seen[kind]}" if totals[kind] > 1 else "")
        links.append(f'[{label}]({source["url"]})')
    return " · ".join(links)


def resources(model):
    release = model["release"]
    covered = {release[key] for key in ("code_url", "weights_url", "code_license_url", "weights_license_url")}
    other = [s for s in model["sources"] if s["url"] not in covered]
    parts = [sources({"sources": other})] if other else []
    parts += [f'[Code]({release["code_url"]})', f'[Weights]({release["weights_url"]})']
    return " · ".join(parts)


def license_links(model):
    release = model["release"]
    return f'**Licenses:** code [{release["code_license"]}]({release["code_license_url"]}) · weights [{release["weights_license"]}]({release["weights_license_url"]})'


def iso_date(value, context):
    if not isinstance(value, str) or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
        raise ValueError(f"{context}: expected YYYY-MM-DD")
    return date.fromisoformat(value)


def validate(catalog):
    if catalog.get("schema_version") != 2:
        raise ValueError("Unsupported schema_version")
    cutoff = iso_date(catalog["as_of"], "as_of")
    models = catalog["models"]
    if not isinstance(models, list) or not models:
        raise ValueError("models must be a nonempty list")
    ids, names = set(), set()
    required = {"id", "name", "category", "inputs", "outputs", "interaction", "architecture", "notes", "variants", "source_date", "source_date_kind", "sources", "release"}
    for m in models:
        if set(m) != required:
            raise ValueError(f'{m.get("id", "entry")}: unexpected/missing fields: {set(m) ^ required}')
        mid = m["id"]
        if not isinstance(mid, str) or not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", mid) or mid in ids:
            raise ValueError(f"Invalid or duplicate id: {mid}")
        ids.add(mid)
        for field in ("name", "architecture", "notes"):
            if not isinstance(m[field], str) or not m[field].strip():
                raise ValueError(f"{mid}: {field} must contain text")
        if m["name"].casefold() in names:
            raise ValueError(f'{mid}: duplicate name; disambiguate separate models')
        names.add(m["name"].casefold())
        if m["category"] not in CATEGORIES or m["interaction"] not in INTERACTIONS:
            raise ValueError(f"{mid}: unknown category or interaction")
        for field in ("inputs", "outputs"):
            values = m[field]
            if not isinstance(values, list) or not values or not all(isinstance(x, str) for x in values) or len(values) != len(set(values)) or not set(values) <= MODALITIES:
                raise ValueError(f"{mid}: invalid {field}")
        variants = m["variants"]
        if not isinstance(variants, list) or not all(isinstance(v, str) and v.strip() for v in variants) or len(variants) != len(set(variants)):
            raise ValueError(f"{mid}: invalid variants")
        if m["source_date"] is None:
            if m["source_date_kind"] is not None:
                raise ValueError(f"{mid}: date kind requires a date")
        elif iso_date(m["source_date"], mid) > cutoff or m["source_date_kind"] not in {"paper", "announcement"}:
            raise ValueError(f"{mid}: invalid or future source date")
        if not isinstance(m["sources"], list) or not m["sources"]:
            raise ValueError(f"{mid}: at least one primary source required")
        urls = set()
        for source in m["sources"]:
            if set(source) != {"kind", "title", "url", "reviewed_on", "review_level"}:
                raise ValueError(f"{mid}: invalid source fields")
            url = urlsplit(source["url"])
            if url.scheme != "https" or not url.netloc or url.username or url.password or source["url"] in urls or re.search(r"\s", source["url"]):
                raise ValueError(f"{mid}: invalid/duplicate HTTPS source")
            urls.add(source["url"])
            if source["kind"] not in SOURCE_KINDS or source["review_level"] not in REVIEWS or not source["title"].strip():
                raise ValueError(f"{mid}: invalid source metadata")
            if iso_date(source["reviewed_on"], mid) > cutoff:
                raise ValueError(f"{mid}: source reviewed after cutoff")
        if m["source_date_kind"] == "paper" and not any(s["kind"] == "paper" for s in m["sources"]):
            raise ValueError(f"{mid}: paper date without a paper source")
        if "T" not in m["inputs"] or not {"I", "V"} & set(m["inputs"]) or not {"A", "S", "M"} & set(m["inputs"]):
            raise ValueError(f"{mid}: omni entries require text, visual and audio inputs")
        release = m["release"]
        release_fields = {"checkpoint", "code_url", "weights_url", "code_license", "weights_license", "code_license_url", "weights_license_url", "weights_revision", "reviewed_on"}
        if not isinstance(release, dict) or set(release) != release_fields:
            raise ValueError(f"{mid}: complete open-source release evidence is required")
        if not all(isinstance(value, str) and value.strip() for value in release.values()):
            raise ValueError(f"{mid}: release fields must contain text")
        if release["code_license"] not in CODE_LICENSES or release["weights_license"] not in WEIGHT_LICENSES:
            raise ValueError(f"{mid}: both code and weights require a supported open license")
        for field in ("code_url", "weights_url", "code_license_url", "weights_license_url"):
            url = urlsplit(release[field])
            if url.scheme != "https" or not url.netloc or url.username or url.password or re.search(r"\s", release[field]) or release[field] not in urls:
                raise ValueError(f"{mid}: {field} must cite a primary HTTPS source")
        if not re.fullmatch(r"[0-9a-f]{40}", release["weights_revision"]):
            raise ValueError(f"{mid}: checkpoint revision must be a full commit hash")
        if iso_date(release["reviewed_on"], mid) > cutoff:
            raise ValueError(f"{mid}: release reviewed after cutoff")
        if m["interaction"] == "full-duplex" and not ({"S", "A"} & set(m["inputs"]) and {"S", "A"} & set(m["outputs"])):
            raise ValueError(f"{mid}: spoken full-duplex requires audio input and output")


def render_category(key, models, cutoff, figures):
    title = CATEGORIES[key][0]
    lines = [f"# {title}", "", GENERATED, "", "[← All models](../README.md#models)", "", f"**{len(models)} models · Reviewed {cutoff}**", "", "Primary-source figures and labeled input/output diagrams. [Figure credits](../assets/architectures/CREDITS.md).", "", '<details>', '<summary>Model index and modality key</summary>', "", LEGEND, "", "Dates refer to papers or announcements, not necessarily model releases.", "", "| Model | Source date | Input → output | Interaction |", "| --- | --- | --- | --- |"]
    for m in models:
        lines.append(f'| [{cell(m["name"])}](#{m["id"]}) | {m["source_date"] or "—"} | {io(m)} | {m["interaction"]} |')
    lines += ["", "</details>", "", "## Architectures", ""]
    for m in models:
        figure = figures[m["id"]]
        visual_type = "Input/output diagram" if figure["kind"] == "io-diagram" else figure["locator"]
        lines += [
            f'<a id="{m["id"]}"></a>', "", f'### {m["name"]}', "",
            m["architecture"].rstrip(".") + ".", "", resources(m), "", license_links(m), "",
            f'![{cell(m["name"])} — {visual_type}](../{figure["path"]})', "",
            f'*{visual_type} · [Source]({figure["source_url"]})*', "",
            "<details>", "<summary>Details</summary>", "",
            f'**Input → output:** {io(m)} · **Interaction:** {m["interaction"]}', "", m["notes"], "",
        ]
        if figure["kind"] == "io-diagram":
            lines += ["Editorial summary of documented inputs and outputs; internal architecture is not shown.", ""]
        if m["variants"]:
            lines += ["**Variants:** " + "; ".join(m["variants"]) + ".", ""]
        lines += ["</details>", ""]
    return "\n".join(lines).rstrip() + "\n"


def render_readme(catalog, figures):
    models = sorted_models(catalog["models"])
    lines = [
        "# Awesome Omni Architectures [![Awesome](https://awesome.re/badge.svg)](https://awesome.re)", "", GENERATED, "",
        "Open-source omni models with public code, downloadable weights and verified licenses. Every entry combines text, vision and audio, with a diagram and primary sources.", "",
        f'**{len(models)} open-source omni models · Reviewed {catalog["as_of"]}**', "",
        "[Model list](#models) · [All diagrams](#model-figures) · [Model details](models/omni.md) · [Timeline](docs/timeline.md) · [Scope and licenses](docs/methodology.md) · [Contribute](CONTRIBUTING.md)", "",
        "## Models", "",
        "T: text · I: image · V: video · A: audio · S: speech · M: music · X: other. [Scope and labels](docs/methodology.md#modalities-and-interaction).", "",
        "<details>", f"<summary>Alphabetical model list · {len(models)} entries</summary>", "",
        "| Model | Input → output | Code license | Weights license |", "| --- | --- | --- | --- |",
    ]
    for m in models:
        release = m["release"]
        lines.append(f'| [{cell(m["name"])}](#{m["id"]}) | {io(m)} | [{release["code_license"]}]({release["code_license_url"]}) | [{release["weights_license"]}]({release["weights_license_url"]}) |')
    lines += ["", "</details>", "", '<a id="architectures"></a>', "", "## Model figures", "", "Figures are credited to their sources. Editorial input/output diagrams are labeled. [Credits](assets/architectures/CREDITS.md).", ""]
    for m in models:
        figure = figures[m["id"]]
        visual_type = "Input/output diagram" if figure["kind"] == "io-diagram" else figure["locator"]
        lines += [
            f'<a id="{m["id"]}"></a>', "", f'### {m["name"]}', "",
            m["architecture"].rstrip(".") + ".", "",
            f'{resources(m)} · [Details]({link(m)})', "", license_links(m), "",
            f'![{cell(m["name"])} — {visual_type}]({figure["path"]})', "",
            f'*{visual_type} · [Source]({figure["source_url"]})*', "",
        ]
    lines += [
        "", "---", "",
        "[JSON catalog](data/models.json) · [Apache 2.0](LICENSE) · [Third-party figure notice](assets/architectures/FIGURE_NOTICE.md)", "",
    ]
    return "\n".join(lines)


def render_timeline(catalog):
    known = [m for m in catalog["models"] if m["source_date"]]
    unknown = sorted_models([m for m in catalog["models"] if not m["source_date"]])
    known.sort(key=lambda m: (m["source_date"], m["name"].casefold()), reverse=True)
    lines = ["# Paper and announcement timeline", "", GENERATED, "", "[← Model index](../README.md#models)", "", f'Reviewed as of **{catalog["as_of"]}**. {len(known)} entries have a verified source date; {len(unknown)} are undated in this catalog.', "", "These are dates of the linked paper or explicitly dated announcement. An arXiv submission can precede or follow model/weights/API availability. A paper's first submission date can also precede the release of variants discussed in later revisions. Repository updates, API snapshot suffixes and model training cutoffs are not treated as release dates.", "", "| Source date | Model | Date type | Primary sources |", "| --- | --- | --- | --- |"]
    for m in known:
        lines.append(f'| {m["source_date"]} | [{cell(m["name"])}]({link(m, "../")}) | {m["source_date_kind"]} | {sources(m)} |')
    lines += ["", "## No established source date", "", "These entries remain searchable without assigning a guessed publication or release date.", ""]
    lines += [f'- [{m["name"]}]({link(m, "../")})' for m in unknown]
    return "\n".join(lines).rstrip() + "\n"


def validate_local_links(outputs):
    """Check generated links and authored Markdown links against local files/anchors."""
    pages = {p: p.read_text(encoding="utf-8") for p in ROOT.rglob("*.md") if ".git" not in p.parts and p.name != "model-template.md"}
    pages.update(outputs)
    anchor_cache = {}
    for path, content in pages.items():
        anchors = set(re.findall(r'<a\s+id="([^"]+)"', content))
        for heading in re.findall(r"^#{1,6}\s+(.+)$", content, re.M):
            slug = re.sub(r"[^\w\- ]", "", heading.lower()).replace(" ", "-")
            anchors.add(slug)
        anchor_cache[path] = anchors
    for path, content in pages.items():
        # Fenced code examples are not navigable Markdown links.
        content = re.sub(r"```.*?```", "", content, flags=re.S)
        targets = re.findall(r"\[[^\]\n]*\]\(([^)\s]+)\)", content)
        targets += re.findall(r'<(?:img|a)\s+[^>]*?(?:src|href)="([^"]+)"', content)
        # Linked image previews contain an outer link around the image.
        targets += re.findall(r"\[!\[[^\]]*\]\([^)]+\)\]\(([^)]+)\)", content)
        for target in targets:
            if urlsplit(target).scheme or target.startswith("//"):
                continue
            relative, _, anchor = target.partition("#")
            dest = (path.parent / relative).resolve() if relative else path
            if dest not in pages and not dest.exists():
                raise ValueError(f"{path.relative_to(ROOT)}: missing link target {target}")
            if anchor and dest in anchor_cache and anchor not in anchor_cache[dest]:
                raise ValueError(f"{path.relative_to(ROOT)}: missing anchor {target}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate without modifying files; fail on stale generated files")
    args = parser.parse_args()
    try:
        catalog = json.loads(DATA.read_text(encoding="utf-8"))
        validate(catalog)
        models = sorted_models(catalog["models"])
        manifest = json.loads(FIGURES.read_text(encoding="utf-8"))
        validate_figures(catalog, manifest, ROOT)
        figures = manifest["models"]
        outputs = {
            ROOT / "README.md": render_readme(catalog, figures),
            ROOT / "docs/timeline.md": render_timeline(catalog),
            ROOT / "assets/architectures/CREDITS.md": render_credits(models, manifest),
        }
        for model in models:
            figure = figures[model["id"]]
            if figure["kind"] == "io-diagram":
                outputs[ROOT / figure["path"]] = render_interface(model)
        for key, (_, filename, _) in CATEGORIES.items():
            outputs[ROOT / "models" / filename] = render_category(key, [m for m in models if m["category"] == key], catalog["as_of"], figures)
        validate_local_links(outputs)
        stale = []
        for path, content in outputs.items():
            if args.check:
                if not path.exists() or path.read_text(encoding="utf-8") != content:
                    stale.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
        if stale:
            raise ValueError("Stale generated files: " + ", ".join(stale) + "; run python3 scripts/catalog.py")
        unique_sources = {s["url"] for m in models for s in m["sources"]}
        print(f'{"Checked" if args.check else "Rendered"} {len(models)} open-source omni entries, {len(unique_sources)} unique primary sources, {len(figures)} model visuals; release evidence, catalog integrity, figure assets and local links OK.')
    except (ValueError, KeyError, TypeError, OSError) as exc:
        print(f"Catalog error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
