#!/usr/bin/env python3
"""Validate the source catalog and render its Markdown views (standard library only)."""

import argparse
from collections import Counter
from datetime import date
import json
from pathlib import Path
import re
import sys
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "models.json"
CATEGORIES = {
    "omni": ("Omni and audio-visual language models", "omni.md", "Omni"),
    "dialogue": ("Spoken dialogue models", "speech-dialogue.md", "Dialogue"),
    "foundation": ("Speech and audio language-model foundations", "speech-foundations.md", "Foundations"),
    "understanding": ("Audio and speech understanding", "audio-understanding.md", "Understanding"),
    "asr": ("LLM-based speech recognition and translation", "llm-asr.md", "ASR"),
    "generation": ("Speech generation and language-model-based TTS", "speech-generation.md", "Generation"),
    "related": ("Related omni models and speech systems", "related.md", "Related"),
}
DESCRIPTIONS = {
    "omni": "Models combining language, audio/speech and vision, plus explicitly identified multimodal systems. Understanding-only models are included: the word omni does not guarantee audio output or any-to-any generation.",
    "dialogue": "Models with a documented spoken-response path. Some entries describe a research configuration or an API model; consult the notes before assuming the same capability in every checkpoint.",
    "foundation": "Textless speech LMs, joint speech-text pretraining, continuation models and general audio-generation foundations. These are not necessarily instruction-following assistants.",
    "understanding": "Speech/audio-conditioned language models that produce text. Speech prompts, audio reasoning and voice-chat input do not by themselves imply speech output.",
    "asr": "Recognition and translation models with a documented language-model connection. Conventional ASR systems and standalone encoders are outside this section's scope.",
    "generation": "Autoregressive, masked-token, diffusion-language-model and continuous-latent LM approaches to speech synthesis. A speech reference in the input column usually conditions voice or continuation; it does not establish speech understanding. Scripted dialogue TTS does not generate the conversational answer itself.",
    "related": "Boundary cases retained for discovery: visual omni models, non-LM multimodal generators and modular voice systems. These entries are counted separately from the main omni/SpeechLM catalog.",
}
MODALITIES = {"T", "I", "V", "A", "S", "M", "X"}
INTERACTIONS = {"generation", "text-output", "streaming", "full-duplex", "not-specified", "system"}
SOURCE_KINDS = {"paper", "repository", "model-card", "documentation", "announcement", "project"}
REVIEWS = {"abstract", "readme", "model-card", "documentation", "announcement", "project"}
LEGEND = "**Modalities:** T = text, I = image, V = video, A = general audio, S = speech, M = music, X = other structured modalities. A is a broad label, not a guarantee of every audio task. See the [methodology](../docs/methodology.md) for interaction labels, variant scope and inclusion rules."
GENERATED = "<!-- Generated by scripts/catalog.py from data/models.json. Edit the JSON, then regenerate. -->"


def cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")


def sorted_models(models):
    return sorted(models, key=lambda m: (m["name"].casefold(), m["id"]))


def link(model, prefix=""):
    return f'{prefix}models/{CATEGORIES[model["category"]][1]}#{model["id"]}'


def io(model):
    return f'{", ".join(model["inputs"])} → {", ".join(model["outputs"])}'


def sources(model):
    labels = {"paper": "Paper", "repository": "Repository", "model-card": "Model card", "documentation": "Docs", "announcement": "Announcement", "project": "Project"}
    totals = Counter(s["kind"] for s in model["sources"])
    seen = Counter()
    links = []
    for source in model["sources"]:
        kind = source["kind"]
        seen[kind] += 1
        label = labels[kind] + (f" {seen[kind]}" if totals[kind] > 1 else "")
        links.append(f'[{label}]({source["url"]})')
    return " · ".join(links)


def iso_date(value, context):
    if not isinstance(value, str) or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
        raise ValueError(f"{context}: expected YYYY-MM-DD")
    return date.fromisoformat(value)


def validate(catalog):
    if catalog.get("schema_version") != 1:
        raise ValueError("Unsupported schema_version")
    cutoff = iso_date(catalog["as_of"], "as_of")
    models = catalog["models"]
    if not isinstance(models, list) or not models:
        raise ValueError("models must be a nonempty list")
    ids, names = set(), set()
    required = {"id", "name", "category", "inputs", "outputs", "interaction", "architecture", "notes", "variants", "source_date", "source_date_kind", "sources"}
    for m in models:
        if set(m) != required:
            raise ValueError(f'{m.get("id", "entry")}: unexpected/missing fields: {set(m) ^ required}')
        mid = m["id"]
        if not isinstance(mid, str) or not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", mid) or mid in ids:
            raise ValueError(f"Invalid or duplicate id: {mid}")
        ids.add(mid)
        for field in ("name", "architecture", "notes"):
            if not isinstance(m[field], str) or not m[field].strip():
                raise ValueError(f"{mid}: {field} must contain text")
        if m["name"].casefold() in names:
            raise ValueError(f'{mid}: duplicate name; disambiguate separate models')
        names.add(m["name"].casefold())
        if m["category"] not in CATEGORIES or m["interaction"] not in INTERACTIONS:
            raise ValueError(f"{mid}: unknown category or interaction")
        for field in ("inputs", "outputs"):
            values = m[field]
            if not isinstance(values, list) or not values or not all(isinstance(x, str) for x in values) or len(values) != len(set(values)) or not set(values) <= MODALITIES:
                raise ValueError(f"{mid}: invalid {field}")
        variants = m["variants"]
        if not isinstance(variants, list) or not all(isinstance(v, str) and v.strip() for v in variants) or len(variants) != len(set(variants)):
            raise ValueError(f"{mid}: invalid variants")
        if m["source_date"] is None:
            if m["source_date_kind"] is not None:
                raise ValueError(f"{mid}: date kind requires a date")
        elif iso_date(m["source_date"], mid) > cutoff or m["source_date_kind"] not in {"paper", "announcement"}:
            raise ValueError(f"{mid}: invalid or future source date")
        if not isinstance(m["sources"], list) or not m["sources"]:
            raise ValueError(f"{mid}: at least one primary source required")
        urls = set()
        for source in m["sources"]:
            if set(source) != {"kind", "title", "url", "reviewed_on", "review_level"}:
                raise ValueError(f"{mid}: invalid source fields")
            url = urlsplit(source["url"])
            if url.scheme != "https" or not url.netloc or url.username or url.password or source["url"] in urls or re.search(r"\s", source["url"]):
                raise ValueError(f"{mid}: invalid/duplicate HTTPS source")
            urls.add(source["url"])
            if source["kind"] not in SOURCE_KINDS or source["review_level"] not in REVIEWS or not source["title"].strip():
                raise ValueError(f"{mid}: invalid source metadata")
            if iso_date(source["reviewed_on"], mid) > cutoff:
                raise ValueError(f"{mid}: source reviewed after cutoff")
        if m["source_date_kind"] == "paper" and not any(s["kind"] == "paper" for s in m["sources"]):
            raise ValueError(f"{mid}: paper date without a paper source")
        if m["interaction"] == "full-duplex" and not ({"S", "A"} & set(m["inputs"]) and {"S", "A"} & set(m["outputs"])):
            raise ValueError(f"{mid}: spoken full-duplex requires audio input and output")
        if m["category"] in {"dialogue", "generation"} and not {"S", "A"} & set(m["outputs"]):
            raise ValueError(f"{mid}: dialogue/generation category requires a speech/audio output path")
        if m["category"] in {"understanding", "asr"} and {"S", "A", "M"} & set(m["outputs"]):
            raise ValueError(f"{mid}: text-output category cannot assert generated audio")


def render_category(key, models, cutoff):
    title = CATEGORIES[key][0]
    lines = [f"# {title}", "", GENERATED, "", "[← Model index](../README.md#models)", "", f"**Reviewed as of {cutoff} · {len(models)} entries.**", "", DESCRIPTIONS[key], "", LEGEND, "", "Dates below refer to the linked paper or announcement, **not necessarily a weights/API release**. An em dash means no date was established from the reviewed source.", "", "| Model | Source date | Input → output | Interaction | Architecture | Primary sources |", "| --- | --- | --- | --- | --- | --- |"]
    for m in models:
        lines.append(f'| [{cell(m["name"])}](#{m["id"]}) | {m["source_date"] or "—"} | {io(m)} | {m["interaction"]} | {cell(m["architecture"])} | {sources(m)} |')
    lines += ["", "## Model notes", ""]
    for m in models:
        lines += [f'<a id="{m["id"]}"></a>', "", f'### {m["name"]}', "", m["notes"], ""]
        if m["variants"]:
            lines += ["**Listed variants:** " + "; ".join(m["variants"]) + ".", ""]
    return "\n".join(lines).rstrip() + "\n"


def render_readme(catalog):
    models = sorted_models(catalog["models"])
    counts = Counter(m["category"] for m in models)
    core = len(models) - counts["related"]
    lines = ["# Awesome Omni Architectures [![Awesome](https://awesome.re/badge.svg)](https://awesome.re)", "", GENERATED, "", "A source-backed catalog of omni models, spoken language models (SpeechLMs), audio-language understanding, LLM-based ASR and language-model-based speech generation.", "", f'**Research snapshot: {catalog["as_of"]}. {core} main catalog entries and {counts["related"]} related entries.** Entries represent named models, meaningful generations or explicitly identified systems; they are not a count of unique base architectures or downloadable checkpoints.', "", "This is a broad, maintained literature and release inventory. Public evidence cannot establish an exhaustive list of every private model, derivative fine-tune, checkpoint or future release. Historical and preview models remain useful research references; inclusion does not imply current API availability or released weights.", "", "[Model index](#models) · [Taxonomy](#taxonomy) · [Dated sources](docs/timeline.md) · [Research methodology](docs/methodology.md) · [JSON catalog](data/models.json) · [Contributing](CONTRIBUTING.md)", "", "## Catalog", "", "| Group | Entries | Scope |", "| --- | ---: | --- |"]
    for key, (title, filename, _) in CATEGORIES.items():
        lines.append(f"| [{title}](models/{filename}) | {counts[key]} | {DESCRIPTIONS[key].split('. ')[0]}. |")
    lines += ["", "Each category includes primary-source links, architecture summaries, input/output modalities, interaction modes, source dates and variant notes. The [JSON](data/models.json) also records source titles and review levels.", "", "## Taxonomy", "", "Omni is used inconsistently in the literature. Here the main omni section covers language models that combine audio/speech with vision, including understanding-only models and labeled systems. SpeechLM coverage also includes speech-only foundations, speech/text assistants and LM-based synthesizers.", "", "| Label | Meaning |", "| --- | --- |", "| T / I / V | Text / image / video. |", "| A / S / M | General audio / speech / music. Speech and music are audio subtypes, not additional independent modalities. |", "| X | Other representations such as grounding coordinates, motion, sensors or actions; described in the entry. |", "| text-output | Listed task produces text or structured text; no audio generation is asserted. |", "| generation | Conditional generation or continuation; no real-time interaction guarantee. |", "| streaming | A source documents incremental processing or generation; this does not establish simultaneous listening and speaking. |", "| full-duplex | A source explicitly describes concurrent listening and spoken output. This is a reported capability, not an independently reproduced measurement. |", "| system | The entry coordinates multiple components, models or external generators. |", "| not-specified | The reviewed evidence does not establish a more specific interaction mode. |", "", "Modality columns describe capabilities documented for the named entry; family rows may span variants. Consult variant notes and the exact checkpoint/API documentation before choosing an implementation. Reference speech for TTS is conditioning, not evidence of spoken question answering. See the [scope rules and architecture guide](docs/methodology.md).", "", "## Models", "", "Alphabetical index of all catalog entries. Follow a model name for its notes and primary sources.", "", "| Model | Group | Input → output |", "| --- | --- | --- |"]
    for m in models:
        lines.append(f'| [{cell(m["name"])}]({link(m)}) | {CATEGORIES[m["category"]][2]} | {io(m)} |')
    lines += ["", "## Research and maintenance", "", "The [methodology](docs/methodology.md) documents the discovery sources, inclusion rules, naming corrections and review limits. The [timeline](docs/timeline.md) uses paper/announcement dates and keeps undated entries separate. These dates are not model release dates.", "", "Edit `data/models.json`, then regenerate the Markdown views and check consistency:", "", "```bash", "python3 scripts/catalog.py", "python3 scripts/catalog.py --check", "```", "", "The validator checks identifiers, modality labels, source metadata, dates, generated-file freshness and local Markdown links. It runs offline and does not test model inference or live endpoint availability. See [CONTRIBUTING.md](CONTRIBUTING.md) for adding a model and the [optional architecture article template](templates/model-template.md) for deeper write-ups.", "", "## License", "", "This repository is licensed under [Apache 2.0](LICENSE). Linked papers, code, weights and services retain their own licenses and terms; this catalog does not relicense them.", ""]
    return "\n".join(lines)


def render_timeline(catalog):
    known = [m for m in catalog["models"] if m["source_date"]]
    unknown = sorted_models([m for m in catalog["models"] if not m["source_date"]])
    known.sort(key=lambda m: (m["source_date"], m["name"].casefold()), reverse=True)
    lines = ["# Paper and announcement timeline", "", GENERATED, "", "[← Model index](../README.md#models)", "", f'Reviewed as of **{catalog["as_of"]}**. {len(known)} entries have a verified source date; {len(unknown)} are undated in this catalog.', "", "These are dates of the linked paper or explicitly dated announcement. An arXiv submission can precede or follow model/weights/API availability. A paper's first submission date can also precede the release of variants discussed in later revisions. Repository updates, API snapshot suffixes and model training cutoffs are not treated as release dates.", "", "| Source date | Model | Date type | Primary sources |", "| --- | --- | --- | --- |"]
    for m in known:
        lines.append(f'| {m["source_date"]} | [{cell(m["name"])}]({link(m, "../")}) | {m["source_date_kind"]} | {sources(m)} |')
    lines += ["", "## No established source date", "", "These entries remain searchable without assigning a guessed publication or release date.", ""]
    lines += [f'- [{m["name"]}]({link(m, "../")})' for m in unknown]
    return "\n".join(lines).rstrip() + "\n"


def validate_local_links(outputs):
    """Check generated links and authored Markdown links against local files/anchors."""
    pages = {p: p.read_text(encoding="utf-8") for p in ROOT.rglob("*.md") if ".git" not in p.parts and p.name != "model-template.md"}
    pages.update(outputs)
    anchor_cache = {}
    for path, content in pages.items():
        anchors = set(re.findall(r'<a\s+id="([^"]+)"', content))
        for heading in re.findall(r"^#{1,6}\s+(.+)$", content, re.M):
            slug = re.sub(r"[^\w\- ]", "", heading.lower()).replace(" ", "-")
            anchors.add(slug)
        anchor_cache[path] = anchors
    for path, content in pages.items():
        # Fenced code examples are not navigable Markdown links.
        content = re.sub(r"```.*?```", "", content, flags=re.S)
        for target in re.findall(r"(?<!!)\[[^\]\n]+\]\(([^)\s]+)\)", content):
            if urlsplit(target).scheme or target.startswith("//"):
                continue
            relative, _, anchor = target.partition("#")
            dest = (path.parent / relative).resolve() if relative else path
            if dest not in pages and not dest.exists():
                raise ValueError(f"{path.relative_to(ROOT)}: missing link target {target}")
            if anchor and dest in anchor_cache and anchor not in anchor_cache[dest]:
                raise ValueError(f"{path.relative_to(ROOT)}: missing anchor {target}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate without modifying files; fail on stale Markdown")
    args = parser.parse_args()
    try:
        catalog = json.loads(DATA.read_text(encoding="utf-8"))
        validate(catalog)
        models = sorted_models(catalog["models"])
        outputs = {ROOT / "README.md": render_readme(catalog), ROOT / "docs/timeline.md": render_timeline(catalog)}
        for key, (_, filename, _) in CATEGORIES.items():
            outputs[ROOT / "models" / filename] = render_category(key, [m for m in models if m["category"] == key], catalog["as_of"])
        validate_local_links(outputs)
        stale = []
        for path, content in outputs.items():
            if args.check:
                if not path.exists() or path.read_text(encoding="utf-8") != content:
                    stale.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
        if stale:
            raise ValueError("Stale generated files: " + ", ".join(stale) + "; run python3 scripts/catalog.py")
        unique_sources = {s["url"] for m in models for s in m["sources"]}
        print(f'{"Checked" if args.check else "Rendered"} {len(models)} entries, {len(unique_sources)} unique primary sources, {len(outputs)} Markdown views; catalog integrity and local links OK.')
    except (ValueError, KeyError, TypeError, OSError) as exc:
        print(f"Catalog error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
